package com.example.viewpagerpoc;

public enum ZoneAFragmentsEnum {
    ZONE_A_FRAGMENT,
    NAVIGATION_FRAGMENT,
    RADIO_FRAGMENT,
    PHONE_FRAGMENT,
    SETTINGS_FRAGMENT,
    USER_FRAGMENT,
    BLUETOOTH_FRAGMENT,


    BLUETOOTH_OPTIONS_FRAGMENT,
    BLUETOOTH_SEARCH_FRAGMENT,
    BLUETOOTH_PHONE_CONNECT_FRAGMENT,
    BLUETOOTH_PHONE_CONTACTS_FRAGMENT
}
